name:                liveshader-hs
version:             0.1.0.0
license:             AGPL-3

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- GLFW
- GLUtil
- OpenGL
- OpenGLRaw
- bytestring
- lens
- mtl
- time
- fsnotify
- stm

default-extensions:
- TemplateHaskell
- GeneralizedNewtypeDeriving
- FlexibleContexts
- RankNTypes
- FlexibleInstances
- MultiParamTypeClasses
- LambdaCase

library:
  source-dirs: src

executables:
  liveshader-hs-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - liveshader-hs